//! Synthetic, browseable history profiles. Bulk insert the operation log and
//! derive live rows from the same Rust projection used by historical reads.
//! This is fixture generation, not a benchmark of production write throughput.
use anyhow::{ensure, Context};
use chrono::{DateTime, Datelike, Duration, Utc};
use serde_json::{json, Value};
use sqlx::{PgPool, Postgres, Transaction};
use uuid::Uuid;

use crate::{
    ops::Op,
    plan::{project_at, LoggedOp},
    seed,
};

const FIXTURE_MARKER: &str = "Generated by plan_history_seed (fixture)";
pub const TRACKS: usize = 3;
pub const SPRINTS: usize = 6;

pub struct Config {
    pub revisions: Vec<usize>,
    pub tasks: usize,
    pub days: i64,
}
impl Default for Config {
    fn default() -> Self {
        Self {
            revisions: vec![1_000, 10_000, 50_000],
            tasks: 200,
            days: 90,
        }
    }
}
impl Config {
    pub fn validate(&self) -> anyhow::Result<()> {
        ensure!(
            (1..=10_000).contains(&self.tasks),
            "--tasks must be between 1 and 10000"
        );
        ensure!(
            (1..=3650).contains(&self.days),
            "--days must be between 1 and 3650"
        );
        ensure!(
            !self.revisions.is_empty(),
            "Provide at least one revision count"
        );
        let mut unique = std::collections::HashSet::new();
        for &count in &self.revisions {
            ensure!(
                (self.tasks + TRACKS + SPRINTS..=1_000_000).contains(&count),
                "Each revision count must cover task/track/sprint creation and be at most 1000000"
            );
            ensure!(unique.insert(count), "Revision profiles must be unique");
        }
        Ok(())
    }
}
pub fn project_id(workspace: Uuid, count: usize) -> Uuid {
    seed::id(&format!("plan_history_stress_{workspace}_{count}"))
}
fn entity(project: Uuid, kind: &str, index: usize) -> Uuid {
    seed::id(&format!("plan_history_stress_{project}_{kind}_{index}"))
}

fn history(
    config: &Config,
    project: Uuid,
    count: usize,
    end: DateTime<Utc>,
) -> anyhow::Result<Vec<LoggedOp>> {
    let first = end - Duration::days(config.days);
    let span = (end - first).num_microseconds().unwrap();
    let mut ops = Vec::with_capacity(count);
    let mut emit = |payload: Value| -> anyhow::Result<()> {
        // Fail the seeder on malformed payloads rather than relying on replay's
        // compatibility behavior, which intentionally ignores unknown shapes.
        let typed: Op = serde_json::from_value(payload.clone())?;
        let index = ops.len();
        ops.push(LoggedOp {
            seq: index as i64 + 1,
            applied_at: first
                + Duration::microseconds(
                    (span as i128 * index as i128 / (count - 1) as i128) as i64,
                ),
            kind: typed.kind_str().into(),
            payload,
        });
        Ok(())
    };
    let colors = ["#2563eb", "#9333ea", "#16a34a"];
    for (i, color) in colors.iter().enumerate() {
        emit(json!({"kind":"track.create", "track":{
            "id":entity(project,"track",i), "project_id":project, "title":(["Product","Platform","Delivery"][i]),
            "color":color, "sort_key":format!("{i:06}")}}))?;
    }
    // Anchor the latest sprints around today so the live board is immediately
    // useful; earlier revisions shift the dates and move tasks between cards.
    let today = end.date_naive();
    let board_start =
        today - Duration::days(today.weekday().num_days_from_monday() as i64) - Duration::weeks(2);
    for i in 0..SPRINTS {
        let start = board_start + Duration::days((i / TRACKS) as i64 * 14);
        emit(json!({"kind":"sprint.create", "sprint":{
            "id":entity(project,"sprint",i), "project_id":project,
            "track_id":entity(project,"track",i % TRACKS), "title":format!("Sprint {}",i+1),
            "starts_on":start, "ends_on":start+Duration::days(14), "sort_key":format!("{i:06}")}}))?;
    }
    for i in 0..config.tasks {
        emit(json!({"kind":"task.create", "task":{
            "id":entity(project,"task",i), "project_id":project, "title":format!("History task {}",i+1),
            "section":"later", "status":"todo", "source":"local", "sort_key":format!("{i:06}"),
            "sprint_id": if i % 5 == 0 { None } else { Some(entity(project,"sprint",i % SPRINTS)) }}}))?;
    }
    let remaining = count - config.tasks - TRACKS - SPRINTS;
    for i in 0..remaining {
        // Advance entity independently of operation kind to exercise every
        // task/sprint, rather than repeatedly ticking the same subset.
        let index = (i / 12 + i % 12 * 17) % config.tasks;
        let task = entity(project, "task", index);
        let sprint_index = (i / 12) % SPRINTS;
        let sprint = entity(project, "sprint", sprint_index);
        let track = entity(project, "track", (i / 12) % TRACKS);
        let payload = match i % 12 {
            0 => {
                json!({"kind":"task.set_title", "task_id":task, "title":format!("Task {} · edit {}",index+1,i+1)})
            }
            1 => json!({"kind":"task.tick", "task_id":task, "done":true}),
            2 => json!({"kind":"task.set_status", "task_id":task, "status":"in_progress"}),
            3 => json!({"kind":"task.set_sprint", "task_id":task,
                "sprint_id":if i / 12 % 4 == 0 { None } else { Some(sprint) }}),
            4 => {
                let start = board_start
                    + Duration::days(
                        (sprint_index / TRACKS) as i64 * 14 + (((i / 12) % 3) as i64 - 1) * 7,
                    );
                json!({"kind":"sprint.set_dates", "sprint_id":sprint, "starts_on":start, "ends_on":start+Duration::days(14)})
            }
            5 => json!({"kind":"sprint.set_track", "sprint_id":sprint, "track_id":track}),
            6 => {
                json!({"kind":"task.set_section", "task_id":task, "section":if i / 12 % 2 == 0 {"now"} else {"later"}})
            }
            7 => {
                let ordered: Vec<_> = (0..config.tasks.min(20))
                    .map(|n| entity(project, "task", (index + n) % config.tasks))
                    .collect();
                json!({"kind":"task.reorder", "project_id":project, "ordered":ordered})
            }
            8 => {
                json!({"kind":"sprint.set_title", "sprint_id":sprint, "title":format!("Sprint {} · revision {}",sprint_index+1,i+1)})
            }
            9 => {
                json!({"kind":"track.set_color", "track_id":track, "color":colors[(i / 12 + 1) % TRACKS]})
            }
            10 => json!({"kind":"task.tick", "task_id":task, "done":false}),
            _ => {
                json!({"kind":"track.set_title", "track_id":track, "title":format!("Track {} · revision {}",(i / 12) % TRACKS+1,i+1)})
            }
        };
        emit(payload)?;
    }
    Ok(ops)
}

pub async fn seed_profiles(pool: &PgPool, workspace: Uuid, config: &Config) -> anyhow::Result<()> {
    config.validate()?;
    let mut tx = pool.begin().await?;
    sqlx::query("SELECT pg_advisory_xact_lock(714032)")
        .execute(&mut *tx)
        .await?;
    let owner: Uuid = sqlx::query_scalar("SELECT created_by FROM workspaces WHERE id=$1")
        .bind(workspace)
        .fetch_optional(&mut *tx)
        .await?
        .context("Workspace not found; seed the normal fixture first or pass --workspace UUID")?;
    let actors: Vec<Uuid> = sqlx::query_scalar(
        "SELECT user_id FROM workspace_members WHERE workspace_id=$1 AND removed_at IS NULL
         ORDER BY (user_id=$2) DESC,user_id LIMIT 4",
    )
    .bind(workspace)
    .bind(owner)
    .fetch_all(&mut *tx)
    .await?;
    ensure!(
        actors.contains(&owner),
        "Workspace creator must be an active member"
    );
    // Replace only projects previously generated by this seeder. Existing
    // projects, their logs, workspace memberships and sessions are untouched.
    let old_projects: Vec<Uuid> =
        sqlx::query_scalar("SELECT id FROM projects WHERE workspace_id=$1 AND description=$2")
            .bind(workspace)
            .bind(FIXTURE_MARKER)
            .fetch_all(&mut *tx)
            .await?;
    sqlx::query("DELETE FROM processed_ops WHERE workspace_id=$1 AND project_id=ANY($2)")
        .bind(workspace)
        .bind(&old_projects)
        .execute(&mut *tx)
        .await?;
    sqlx::query("DELETE FROM projects WHERE workspace_id=$1 AND id=ANY($2)")
        .bind(workspace)
        .bind(&old_projects)
        .execute(&mut *tx)
        .await?;
    let end =
        DateTime::from_timestamp_micros((Utc::now() - Duration::minutes(1)).timestamp_micros())
            .unwrap();
    for &count in &config.revisions {
        let project = project_id(workspace, count);
        sqlx::query("INSERT INTO projects(id,title,color,source,owner_id,workspace_id,created_at,description) VALUES($1,$2,'#2563eb','local',$3,$4,$5,$6)")
            .bind(project).bind(format!("History · {count} revisions")).bind(owner).bind(workspace)
            .bind(end-Duration::days(config.days)).bind(FIXTURE_MARKER).execute(&mut *tx).await?;
        for (i, actor) in actors.iter().enumerate() {
            sqlx::query("INSERT INTO project_members(project_id,user_id,workspace_id,role) VALUES($1,$2,$3,$4)")
                .bind(project).bind(actor).bind(workspace).bind(if i == 0 {"owner"} else {"member"}).execute(&mut *tx).await?;
        }
        let ops = history(config, project, count, end)?;
        for chunk in ops.chunks(1_000) {
            let records: Vec<_> = chunk.iter().map(|op| json!({
                "op_id":Uuid::new_v4().to_string(), "user_id":actors[(op.seq as usize-1) % actors.len()],
                "kind":op.kind, "payload":op.payload, "applied_at":op.applied_at,
            })).collect();
            // Ordered insertion makes the actual sequence agree with replay's
            // local ordering. All profiles commit together, without WS nudges.
            sqlx::query("INSERT INTO processed_ops(op_id,user_id,workspace_id,project_id,kind,payload,applied_at)
                SELECT r.data->>'op_id',(r.data->>'user_id')::uuid,$1,$2,r.data->>'kind',r.data->'payload',(r.data->>'applied_at')::timestamptz
                FROM jsonb_array_elements($3) WITH ORDINALITY AS r(data,ordinality)
                ORDER BY r.ordinality")
                .bind(workspace).bind(project).bind(json!(records)).execute(&mut *tx).await?;
        }
        let state = project_at(&ops, end);
        materialize(&mut tx, owner, end, &state)
            .await
            .context("Materializing projected live rows")?;
        println!(
            "  History · {count} revisions: {} tasks, {} tracks, {} sprints, {} days",
            state.tasks.len(),
            state.tracks.len(),
            state.sprints.len(),
            config.days
        );
    }
    tx.commit().await?;
    sqlx::query("ANALYZE processed_ops").execute(pool).await?;
    Ok(())
}

async fn materialize(
    tx: &mut Transaction<'_, Postgres>,
    owner: Uuid,
    end: DateTime<Utc>,
    state: &crate::plan::PlanState,
) -> anyhow::Result<()> {
    sqlx::query("INSERT INTO tracks(id,project_id,title,color,sort_key)
        SELECT id,project_id,title,color,sort_key FROM jsonb_to_recordset($1) AS r(id uuid,project_id uuid,title text,color text,sort_key text)")
        .bind(json!(state.tracks)).execute(&mut **tx).await?;
    sqlx::query("INSERT INTO sprints(id,project_id,track_id,title,starts_on,ends_on,sort_key)
        SELECT id,project_id,track_id,title,starts_on,ends_on,sort_key FROM jsonb_to_recordset($1)
        AS r(id uuid,project_id uuid,track_id uuid,title text,starts_on date,ends_on date,sort_key text)")
        .bind(json!(state.sprints)).execute(&mut **tx).await?;
    sqlx::query("INSERT INTO tasks(id,project_id,track_id,sprint_id,title,section,status,sort_key,created_at,finished_at,updated_at,created_by,assignee_id,source)
        SELECT id,project_id,track_id,sprint_id,title,section,status,sort_key,created_at,finished_at,$2,$3,$3,'local'
        FROM jsonb_to_recordset($1) AS r(id uuid,project_id uuid,track_id uuid,sprint_id uuid,title text,section text,status text,sort_key text,created_at timestamptz,finished_at timestamptz)")
        .bind(json!(state.tasks)).bind(end).bind(owner).execute(&mut **tx).await?;
    Ok(())
}
